#include "TPM.h"
void PWM_Init()
{
	SIM->SCGC5 |= SIM_SCGC5_PORTB_MASK;
	PORTB->PCR[6] |= PORT_PCR_MUX(2);		//	TPM0_CH3
	PORTB->PCR[7] |= PORT_PCR_MUX(2);		//	TPM0_CH2
	PTB->PDDR |= (1<<6)|(1<<7);
	
	SIM->SCGC6 |= SIM_SCGC6_TPM0_MASK;
	SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1);
	
	TPM0->SC &= ~TPM_SC_CPWMS_MASK;
	TPM0->SC |= TPM_SC_PS(6);
	TPM0->MOD = 0x3331;
	TPM0->CONTROLS[2].CnSC = TPM_CnSC_MSB_MASK|TPM_CnSC_ELSB_MASK;
	TPM0->CONTROLS[3].CnSC = TPM_CnSC_MSB_MASK|TPM_CnSC_ELSB_MASK;
	TPM0->SC |= TPM_SC_CMOD(1);
}
